### PR TITLE
Remove unnecessary buffer

### PR DESCRIPTION
**Pull request by Sytten**
I managed to removed the partial buffer with a better matching algorithm.
I don't think I missed edge cases. Essentially it remembers the match position of the needle in-between loop runs so it restarts from that position in the needle.

### CODE REVIEW

**Comment by programingjd** [comment]
I spent some time to make sure that all the corner cases were covered also. At first I wasn't sure that match_len would be reset correctly if there was no match, but it is.
I've updated the comment, renamed the test, and merged the changes.
Thank you very much for your contribution.

**Comment by programingjd** [comment]
I've pushed the update to crates.io with version 0.1.3

**Comment by Sytten** [comment]
Thanks! I will try to push into native tokio, but it's likely to be rejected so its good we have it here

**Comment by Sytten** [comment]
Linked PR https://github.com/tokio-rs/tokio/pull/6531, we will see if it gets accepted

**Pull request merged**
